In [1]:
import pandas as pd
import numpy as np

In [26]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [15]:
data = pd.read_csv('train.csv').drop(columns=['Unnamed: 0', 'id'])

In [16]:
data.head()

Gender      Customer Type  Age   Type of Travel     Class  Flight Distance  \
0    Male     Loyal Customer   13  Personal Travel  Eco Plus              460   
1    Male  disloyal Customer   25  Business travel  Business              235   
2  Female     Loyal Customer   26  Business travel  Business             1142   
3  Female     Loyal Customer   25  Business travel  Business              562   
4    Male     Loyal Customer   61  Business travel  Business              214   

   Inflight wifi service  Departure/Arrival time convenient  \
0                      3                                  4   
1                      3                                  2   
2                      2                                  2   
3                      2                                  5   
4                      3                                  3   

   Ease of Online booking  Gate location  ...  Inflight entertainment  \
0                       3              1  ...                       5   
1                       3              3  ...                       1   
2                       2              2  ...                       5   
3                       5              5  ...                       2   
4                       3              3  ...                       3   

   On-board service  Leg room service  Baggage handling  Checkin service  \
0                 4                 3                 4                4   
1                 1                 5                 3                1   
2                 4                 3                 4                4   
3                 2                 5                 3                1   
4                 3                 4                 4                3   

   Inflight service  Cleanliness  Departure Delay in Minutes  \
0                 5            5                          25   
1                 4            1                           1   
2                 4            5                           0   
3                 4            2                          11   
4                 3            3                           0   

   Arrival Delay in Minutes             satisfaction  
0                      18.0  neutral or dissatisfied  
1                       6.0  neutral or dissatisfied  
2                       0.0                satisfied  
3                       9.0  neutral or dissatisfied  
4                       0.0                satisfied  

[5 rows x 23 columns]

In [17]:
data.isnull().sum()

Gender                                 0
Customer Type                          0
Age                                    0
Type of Travel                         0
Class                                  0
Flight Distance                        0
Inflight wifi service                  0
Departure/Arrival time convenient      0
Ease of Online booking                 0
Gate location                          0
Food and drink                         0
Online boarding                        0
Seat comfort                           0
Inflight entertainment                 0
On-board service                       0
Leg room service                       0
Baggage handling                       0
Checkin service                        0
Inflight service                       0
Cleanliness                            0
Departure Delay in Minutes             0
Arrival Delay in Minutes             310
satisfaction                           0
dtype: int64

In [18]:
data.shape

(103904, 23)

In [19]:
data.dropna(inplace=True)

In [20]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 103594 entries, 0 to 103903
Data columns (total 23 columns):
 #   Column                             Non-Null Count   Dtype  
---  ------                             --------------   -----  
 0   Gender                             103594 non-null  object 
 1   Customer Type                      103594 non-null  object 
 2   Age                                103594 non-null  int64  
 3   Type of Travel                     103594 non-null  object 
 4   Class                              103594 non-null  object 
 5   Flight Distance                    103594 non-null  int64  
 6   Inflight wifi service              103594 non-null  int64  
 7   Departure/Arrival time convenient  103594 non-null  int64  
 8   Ease of Online booking             103594 non-null  int64  
 9   Gate location                      103594 non-null  int64  
 10  Food and drink                     103594 non-null  int64  
 11  Online boarding                    103594 no

In [24]:
for column in data.columns:
    unicol = data[column].unique()
    print(unicol)

['Male' 'Female']
['Loyal Customer' 'disloyal Customer']
[13 25 26 61 47 52 41 20 24 12 53 33 45 38  9 17 43 58 23 57 49 36 22 31
 15 35 67 37 40 34 39 50 29 54 21 28 27 69 60 48 59 46 30 66 64 44 51 32
 19 42 16 11 62  8 56 68 55 18 65 72 70 63 10  7 14 80 74 71 85 73 76 77
 75 79 78]
['Personal Travel' 'Business travel']
['Eco Plus' 'Business' 'Eco']
[ 460  235 1142 ...  974 1479  400]
[3 2 4 1 5 0]
[4 2 5 3 1 0]
[3 2 5 4 1 0]
[1 3 2 5 4 0]
[5 1 2 4 3 0]
[3 5 2 1 4 0]
[5 1 2 3 4 0]
[5 1 2 3 4 0]
[4 1 2 3 5 0]
[3 5 4 2 1 0]
[4 3 5 1 2]
[4 1 3 5 2 0]
[5 4 3 1 2 0]
[5 1 2 3 4 0]
[  25    1    0   11    9    4   28   43   49    7   17   52   54   27
   18   19    3  109   23    8   14   10   51   39   13   30   64   20
   45   44   31   81   35   67   22   40   91   21   15   29  105   12
  162   24  141    6   34    2   97   16   99   37   66   53   36  209
   60  149   26    5   59   62  113   38   83  176   46   73  199   56
   93   70   80   96   57   95   74  172   63  175  143   48

In [25]:
data.sample(5)

Gender      Customer Type  Age   Type of Travel     Class  \
101289   Male     Loyal Customer   59  Business travel  Business   
63063    Male     Loyal Customer   24  Personal Travel       Eco   
32284    Male     Loyal Customer   55  Business travel  Business   
81136    Male  disloyal Customer   37  Business travel  Business   
79812    Male     Loyal Customer   16  Business travel  Business   

        Flight Distance  Inflight wifi service  \
101289              954                      4   
63063               546                      3   
32284               500                      1   
81136               166                      4   
79812              3922                      1   

        Departure/Arrival time convenient  Ease of Online booking  \
101289                                  4                       4   
63063                                   5                       3   
32284                                   5                       5   
81136                                   4                       4   
79812                                   1                       5   

        Gate location  ...  Inflight entertainment  On-board service  \
101289              4  ...                       4                 4   
63063               1  ...                       5                 3   
32284               5  ...                       1                 1   
81136               1  ...                       5                 5   
79812               1  ...                       1                 4   

        Leg room service  Baggage handling  Checkin service  Inflight service  \
101289                 4                 4                3                 4   
63063                  3                 5                4                 3   
32284                  1                 1                4                 1   
81136                  2                 4                3                 5   
79812                  2                 3                1                 4   

        Cleanliness  Departure Delay in Minutes  Arrival Delay in Minutes  \
101289            5                          52                      59.0   
63063             5                           0                       2.0   
32284             4                           0                      27.0   
81136             5                           0                       0.0   
79812             1                          52                      49.0   

                   satisfaction  
101289                satisfied  
63063   neutral or dissatisfied  
32284   neutral or dissatisfied  
81136   neutral or dissatisfied  
79812   neutral or dissatisfied  

[5 rows x 23 columns]

In [28]:
X_train, X_test, y_train, y_test = train_test_split(data.drop(columns='satisfaction'), data['satisfaction'], test_size=0.2, random_state=2)
X_train.shape, X_test.shape

((82875, 22), (20719, 22))

In [29]:
ohe = OneHotEncoder(sparse_output= False, handle_unknown='ignore')

data_gen_tr = ohe.fit_transform(X_train[['Gender']])
data_cutype_tr = ohe.fit_transform(X_train[['Customer Type']])
data_travel_tr = ohe.fit_transform(X_train[['Type of Travel']])
data_class_tr = ohe.fit_transform(X_train[['Class']])

data_gen_te = ohe.fit_transform(X_test[['Gender']])
data_cutype_te = ohe.fit_transform(X_test[['Customer Type']])
data_travel_te = ohe.fit_transform(X_test[['Type of Travel']])
data_class_te = ohe.fit_transform(X_test[['Class']])

In [30]:
data.columns

Index(['Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [36]:
data_rem_tr = X_train.drop(columns=['Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class'], axis=1)
data_rem_te = X_test.drop(columns=['Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class'], axis=1)

In [37]:
data_rem_tr.shape, data_rem_te.shape

((82875, 17), (20719, 17))

In [43]:
X_train_final = np.concatenate([data_rem_tr, data_gen_tr, data_cutype_tr, data_travel_tr, data_class_tr], axis = 1)
X_test_final = np.concatenate([data_rem_te, data_gen_te, data_cutype_te, data_travel_te, data_class_te], axis = 1)

In [46]:
X_train_final.shape, X_test_final.shape

((82875, 26), (20719, 26))

In [48]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train_final = le.fit_transform(y_train)
y_test_final = le.transform(y_test)

In [51]:
y_test

44945    neutral or dissatisfied
8835                   satisfied
96739                  satisfied
89593    neutral or dissatisfied
82234                  satisfied
                  ...           
21561                  satisfied
65948    neutral or dissatisfied
62001    neutral or dissatisfied
91055    neutral or dissatisfied
28996    neutral or dissatisfied
Name: satisfaction, Length: 20719, dtype: object

In [52]:
from sklearn.metrics import accuracy_score

In [73]:
lr = LinearRegression()

lr.fit(X_train_final, y_train_final)
y_pred = lr.predict(X_test_final)

print('train score : ',lr.score(X_train_final, y_train_final))
print('test score : ',lr.score(X_test_final, y_test_final))

train score :  0.5545045043963237
test score :  0.5402257512075511


In [74]:
lo = LogisticRegression()

lo.fit(X_train_final, y_train_final)
y_predd = lo.predict(X_test_final)

print('train score : ',lo.score(X_train_final, y_train_final))
print('test score : ', lo.score(X_test_final, y_test_final))

train score :  0.8166877828054299
test score :  0.8109464742506878


C:\Users\Bhavy\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [64]:
clf = DecisionTreeClassifier()

clf.fit(X_train_final, y_train_final)
y_pred_clf = clf.predict(X_test_final)

accuracy_score(y_pred_clf, y_test_final)

0.9421786765770549